# Usa una imagen base de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo de requerimientos a la imagen
COPY requirements.txt .

# Instala las dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Instala pdf2image
RUN pip install pdf2image

# Instala Poppler (necesario para pdf2image)
RUN apt-get update && apt-get install -y poppler-utils

# Copia el resto de los archivos de la aplicación al contenedor
COPY . .

# Expone el puerto donde se ejecutará Streamlit
EXPOSE 8501

# Comando para iniciar la aplicación
CMD ["streamlit", "run", "app.py"]
