# Usa una imagen base oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos locales en el contenedor
COPY . /app

# Instala las dependencias necesarias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Expone el puerto en el que Streamlit correrá
EXPOSE 8501

# Comando para ejecutar la aplicación Streamlit
CMD ["streamlit", "run", "app.py"]
